all:
	# make -f MakefileGen all
	# make -f MakefileTest all
	make -f MakefileChacha20 all
	make -f MakefileChacha20Test all

clean:
	# make -f MakefileGen clean
	# make -f MakefileTest clean
	make -f MakefileChacha20 clean
	make -f MakefileChacha20Test clean

